# Generated by Django 3.0.5 on 2020-04-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='auther',
            new_name='author',
        ),
    ]
