# Generated by Django 3.0 on 2020-04-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200410_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
    ]
